apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: normal
spec:
  project: default
  source:
    repoURL: https://github.com/harish3433/acspolicies.git
    targetRevision: master
    path: policies
  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    jsonPointers:
    - /data
