apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acs-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/acs-policies.git
    targetRevision: HEAD
    path: policies
  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    jsonPointers:
    - /data
