---
- name: Complete ACS Policy GitOps Setup
  hosts: localhost
  gather_facts: false
  vars:
    acs_token: "{{ lookup('env', 'ACS_TOKEN') | default('eyJhbGciOiJSUzI1NiIsImtpZCI6Imp3dGswIiwidHlwIjoiSldUIn0.eyJFeHBpcmVBdCI6IjIwMjYtMTAtMTVUMDc6MDA6MDBaIiwiYXVkIjoiaHR0cHM6Ly9zdGFja3JveC5pby9qd3Qtc291cmNlcyNhcGktdG9rZW5zIiwiZXhwIjoxNzkyMDQ3NjAwLCJpYXQiOjE3NTk2NzQzOTIsImlzcyI6Imh0dHBzOi8vc3RhY2tyb3guaW8vand0IiwianRpIjoiYjQyNDc0NWItMTk2YS00Y2YyLWIyNDgtY2E2OGQ5YTQ1MzRhIiwibmFtZSI6InRlc3QyIiwicm9sZXMiOlsiQWRtaW4iXX0.ASFHfEMKgNo_UifO0te5bDr_ZjFDDu4bI6Ckl6WvjcjnudQyqiVMy3I9bSpMS7-W2hz4QQvJyliNsDWNnp6rTLTu6ZZP4EdLuVL3tbc3sKzbr0fvaM_J5AWhdddo1Nde2pLgHo4WCpvjZgiwDPdXByG--v86Di6-YunXUYQAZMHSSORj2_3Hx4Fnd6ncmGW_Z26UTiW0VYjy-bg_QxpnvtssN2DE1WZqAK6QQE6AFRyr0prq0KSid-s6x7VkN0Pqkgs7BSwPD6qH1DZOvshPtXrdjBpct78ok5GSArwD41ruTAV6FOTflwmtj3_OJKikfqJxHzFLBCpjYSVs6t4llw97Eun96OLodLfvkXuEIJsseWK1pgA5RM-j99mxF9fP9MbIOul7Uq2u2JRSfogNsw-8XNG1VCA_JaHMpH23ZF8JHBGfjxXmt60_rT16pPyGO5ssgPKTb3PVoDNujx3s6gQr01IyicXPtdg638YBLztWw4edxmLIo-EgzkTyxnLfGG9Zr6NwXVbrkFIz9Ja50zdnUvjSTbTYxJeX1goI_enlGoboaekOZUqmPl4z9r8fRLCe2Dn8RPvqd8P3dEK7bF7EgQ2A4QzJTXpMvRA9lHH0ZtkiAj1C-NEj-XUVlQnKTRpfj_GudEi5SsBnjIvFAw-fCkGCjJr4FGdnF8qTHVs') }}"
    github_repo: "https://github.com/harish3433/acspolicies.git"
    acs_central_url: "https://central-rhacs-operator.apps.prince-cluster.ocp02.demo"
    
  tasks:
    - name: Verify ACS token is provided
      debug:
        msg: "Using ACS token (first 20 chars): {{ acs_token[:20] }}..."
      when: acs_token != ""

    - name: Create namespaces
      kubernetes.core.k8s:
        name: "{{ item }}"
        api_version: v1
        kind: Namespace
        state: present
      loop:
        - stackrox
        - argocd

    - name: Check if ArgoCD exists
      kubernetes.core.k8s_info:
        api_version: argoproj.io/v1alpha1
        kind: ArgoCD
        name: argocd
        namespace: argocd
      register: argocd_check
      ignore_errors: true

    - name: Install ArgoCD operator (if not exists)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: argocd-operator
            namespace: argocd
          spec:
            channel: stable
            name: argocd-operator
            source: operatorhub
            sourceNamespace: openshift-marketplace
      when: argocd_check.resources is not defined or argocd_check.resources | length == 0

    - name: Wait for operator
      pause:
        seconds: 30
      when: argocd_check.resources | length == 0

    - name: Install ArgoCD instance (if not exists)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: ArgoCD
          metadata:
            name: argocd
            namespace: argocd
          spec:
            server:
              route:
                enabled: true
      when: argocd_check.resources is not defined or argocd_check.resources | length == 0

    - name: Wait for ArgoCD
      pause:
        seconds: 60
      when: argocd_check.resources is not defined or argocd_check.resources | length == 0

    - name: Create ACS token secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: acs-token
            namespace: stackrox
          type: Opaque
          data:
            token: "{{ acs_token | b64encode }}"

    - name: Configure ArgoCD for faster sync
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: argocd-cmd-params-cm
            namespace: argocd
          data:
            repo.server.timeout.seconds: "60"

    - name: Create ArgoCD application for policies
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: acs-policies
            namespace: argocd
            annotations:
              argocd.argoproj.io/refresh: normal
          spec:
            project: default
            source:
              repoURL: "{{ github_repo }}"
              targetRevision: master
              path: policies
            destination:
              server: https://kubernetes.default.svc
              namespace: stackrox
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              retry:
                limit: 5
                backoff:
                  duration: 5s
                  factor: 2
                  maxDuration: 3m
              syncOptions:
              - CreateNamespace=true

    - name: Get ArgoCD route
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: argocd-server
        namespace: argocd
      register: argocd_route

    - name: Get ArgoCD admin password
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: argocd-cluster
        namespace: argocd
      register: argocd_secret

    - name: Display setup completion
      debug:
        msg: |
          ✅ Complete ACS Policy GitOps Setup Finished!
          
          🌐 ArgoCD UI:
          URL: https://{{ argocd_route.resources[0].spec.host | default('Check: oc get route argocd-server -n argocd') }}
          Username: admin
          Password: {{ argocd_secret.resources[0].data['admin.password'] | b64decode | default('Check: oc get secret argocd-cluster -n argocd -o jsonpath="{.data.admin\.password}" | base64 -d') }}
          
          🎯 ACS Central: {{ acs_central_url }}
          
          📁 Policies Location: GitHub repo /policies folder
          
          🚀 GitOps Flow:
          1. Edit policies in GitHub /policies folder
          2. Push to master branch
          3. ArgoCD auto-syncs within 3 minutes
          4. Policies appear in ACS Central
          
          ✨ Your pipeline is ready!
