apiVersion: v1
kind: ConfigMap
metadata:
  name: container-security-policy
data:
  policy.json: |
    {
      "name": "Container Security Best Practices",
      "description": "Enforce container security standards - no root user, read-only filesystem",
      "rationale": "Running containers as root or with writable filesystem increases security risks",
      "remediation": "Set runAsNonRoot: true and readOnlyRootFilesystem: true in securityContext",
      "disabled": false,
      "categories": ["Security Best Practices", "Container Security"],
      "lifecycleStages": ["DEPLOY"],
      "eventSource": "NOT_APPLICABLE",
      "exclusions": [],
      "scope": [],
      "severity": "HIGH_SEVERITY",
      "enforcementActions": [],
      "notifiers": [],
      "policyVersion": "1.0",
      "policySections": [
        {
          "sectionName": "Container Configuration",
          "policyGroups": [
            {
              "fieldName": "Container Security Context",
              "booleanOperator": "OR",
              "negate": false,
              "values": [
                {"value": "runAsNonRoot=false"},
                {"value": "readOnlyRootFilesystem=false"}
              ]
            }
          ]
        }
      ],
      "mitreAttackVectors": ["TA0004"],
      "criteriaLocked": false,
      "mitreVectorsLocked": false,
      "isDefault": false,
      "source": "IMPERATIVE"
    }
