apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-policy
data:
  policy.json: |
    {
      "name": "docker",
      "description": "",
      "rationale": "",
      "remediation": "",
      "disabled": false,
      "categories": [
        "Anomalous Activity"
      ],
      "lifecycleStages": [
        "BUILD"
      ],
      "eventSource": "NOT_APPLICABLE",
      "exclusions": [],
      "scope": [],
      "severity": "CRITICAL_SEVERITY",
      "enforcementActions": [],
      "notifiers": [],
      "policyVersion": "1.1",
      "policySections": [
        {
          "sectionName": "Rule 1",
          "policyGroups": [
            {
              "fieldName": "Image Registry",
              "booleanOperator": "OR",
              "negate": false,
              "values": [
                {
                  "value": "registry-1.docker.io/babbalrai"
                }
              ]
            }
          ]
        }
      ],
      "mitreAttackVectors": [],
      "criteriaLocked": false,
      "mitreVectorsLocked": false,
      "isDefault": false,
      "source": "IMPERATIVE"
    }
