apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- policy-sync-job.yml

configMapGenerator:
- name: acs-policies
  files:
  - container-security-policy.yml
  - privileged-container-policy.yml

generatorOptions:
  disableNameSuffixHash: false
  labels:
    app.kubernetes.io/instance: acs-policies
