apiVersion: batch/v1
kind: Job
metadata:
  name: acs-policy-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: policy-sync
        image: curlimages/curl:latest
        env:
        - name: ACS_TOKEN
          valueFrom:
            secretKeyRef:
              name: acs-token
              key: token
        - name: ACS_CENTRAL_URL
          value: "https://central-stackrox.apps.prince-cluster.ocp02.demo"
        volumeMounts:
        - name: policies-dev
          mountPath: /policies-dev
        - name: policies-prod
          mountPath: /policies-prod
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Syncing policies to ACS Central..."
          for policy in /policies-dev/*.yml; do
            echo "Processing $policy"
            curl -k -X POST \
              -H "Authorization: Bearer $ACS_TOKEN" \
              -H "Content-Type: application/json" \
              -d @"$policy" \
              "$ACS_CENTRAL_URL/v1/policies" || echo "Policy sync failed for $policy"
          done
          echo "Policy sync completed"
      volumes:
      - name: policies-dev
        configMap:
          name: acs-policies-dev
      - name: policies-prod
        configMap:
          name: acs-policies-prod
      restartPolicy: OnFailure
