apiVersion: batch/v1
kind: Job
metadata:
  name: acs-policy-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: policy-sync
        image: registry.access.redhat.com/ubi8/ubi-minimal:latest
        env:
        - name: ACS_TOKEN
          valueFrom:
            secretKeyRef:
              name: acs-token
              key: token
        - name: ACS_CENTRAL_URL
          value: "https://central-rhacs-operator.apps.prince-cluster.ocp02.demo"
        command: ["/bin/bash"]
        args:
        - -c
        - |
          microdnf install -y curl
          echo "Syncing policies to ACS Central at $ACS_CENTRAL_URL"
          
          # Test connection
          curl -k -s "$ACS_CENTRAL_URL/v1/ping" || exit 1
          
          # Update the 30-day scan policy
          curl -k -X PUT \
            -H "Authorization: Bearer $ACS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "id": "a3eb6dbe-e9ca-451a-919b-216cf7ee11f5",
              "name": "UPDATED-30-Day Scan Age Policy",
              "description": "🔥 LIVE GITOPS TEST - Alert on deployments with images that havent been scanned in 30 days",
              "severity": "CRITICAL_SEVERITY",
              "disabled": false,
              "categories": ["Security Best Practices", "Supply Chain Security"],
              "lifecycleStages": ["DEPLOY"],
              "policyVersion": "1.1",
              "policySections": [{
                "policyGroups": [{
                  "fieldName": "Image Scan Age",
                  "values": [{"value": "30"}]
                }]
              }]
            }' \
            "$ACS_CENTRAL_URL/v1/policies/a3eb6dbe-e9ca-451a-919b-216cf7ee11f5"
          
          echo "Policy sync completed"
      restartPolicy: OnFailure
